StocksApp/ViewModels/Orders.cs
using ServiceContracts.DTO;

namespace StocksApp.ViewModels
{
    public class Orders
    {
        public List<BuyOrderResponse>? BuyOrders  { get; set; }
        public List<SellOrderResponse>? SellOrders { get; set; }

    }
}

StocksApp/ViewModels/Stock.cs
namespace StocksApp.ViewModels
{
    public class Stock
    {
        public string? StockSymbol { get; set; }
        public string? StockName { get; set; }

    }
}

StocksApp/ViewModels/StockTrade.cs
namespace StocksApp.Models
{
    public class StockTrade
    {
        public string? StockSymbol { get; set; }
        public string? StockName { get; set; }
        public double Price { get; set; }
        public string? Logo { get; set; } = string.Empty;
        public string? Industry { get; set; } = string.Empty;
        public string? Exchange { get; set; } = string.Empty;
        public uint Quantity { get; set; }
    }
}

StocksApp/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Model;
using ServiceContracts;
using StocksApp.ViewModels;
using System.Linq;

namespace StocksApp.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly IFinnhubService _finnhubService;
        private readonly IConfiguration _configuration;

        public StocksController(IFinnhubService finnhubService, IConfiguration configuration)
        {
            _configuration = configuration;
            _finnhubService = finnhubService;
        }

        [Route("[action]")]
        [Route("[action]/{stockSymbol}")]

        public async Task<IActionResult> Explore(string stockSymbol)
        {
            var stockSymbols = _configuration["TradingOptions:Top25PopularStocks"]?.Split(",").ToList();
            var stockDictionaryList = await _finnhubService.GetStocks();
            var stocks = new List<Stock>();

            foreach (var stock in stockDictionaryList)
            {
                if (!stockSymbols.Contains(stock["symbol"])) continue;
                stocks.Add(new Stock
                {
                    StockName = stock["description"],
                    StockSymbol = stock["symbol"]
                });
            }

            ViewBag.StockSymbol = stockSymbol;
            return View(stocks.OrderBy(stock => stock.StockName).ToList());
        }
    }
}

StocksApp/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using StocksApp.Models;
using ServiceContracts;
using ServiceContracts.DTO;
using StocksApp.ViewModels;

namespace StocksApp.Controllers
{
    [Route("[controller]/[action]")]
    public class TradeController : Controller
    {
        private readonly IFinnhubService _finnhubService;
        private readonly IStocksService _stocksService;
        private readonly IConfiguration _configuration;

        public TradeController(IFinnhubService finnhubService, IConfiguration configuration, IStocksService stocksService)
        {
            _finnhubService = finnhubService;
            _configuration = configuration;
            _stocksService = stocksService;
        }

        [Route("/")]
        [Route("{stockSymbolFromUser}")]
        public async Task<IActionResult> Index([FromRoute] string? stockSymbolFromUser)
        {
            stockSymbolFromUser = stockSymbolFromUser == "favicon.ico" ? null : stockSymbolFromUser;
            var stockSymbol = stockSymbolFromUser ?? _configuration["TradingOptions:DefaultStockSymbol"];
            var companyProfileDictionary = await _finnhubService.GetCompanyProfile(stockSymbol);
            var stockQuoteDictionary = await _finnhubService.GetStockPriceQuote(stockSymbol);
            ViewBag.FinnhubToken = _configuration["FinnhubToken"] ?? throw new KeyNotFoundException();
            var stockTrade = new StockTrade
            {
                StockSymbol = companyProfileDictionary["ticker"].ToString(),
                StockName = companyProfileDictionary["name"].ToString(),
                Price = double.Parse(stockQuoteDictionary["c"].ToString().Replace('.', ','))
            };
            return View(stockTrade);
        }


        [HttpPost]
        public async Task<IActionResult> BuyOrder(BuyOrderRequest buyOrderRequest)
        {
            buyOrderRequest.DateAndTimeOfOrder = DateTime.Now;
            await _stocksService.CreateBuyOrder(buyOrderRequest);
            return RedirectToAction(nameof(Orders));
        }

        [HttpPost]
        public async Task<IActionResult> SellOrder(SellOrderRequest sellOrderRequest)
        {
            sellOrderRequest.DateAndTimeOfOrder = DateTime.Now;
            await _stocksService.CreateSellOrder(sellOrderRequest);
            return RedirectToAction(nameof(Orders));
        }

        public async Task<IActionResult> Orders()
        {
            var orders = new Orders
            {
                BuyOrders = await _stocksService.GetBuyOrders(),
                SellOrders = await _stocksService.GetSellOrders()
            };
            return View(orders);
        }
    }
}

StocksApp/ViewComponents/SelectedStockViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;
using StocksApp.Models;
using StocksApp.ViewModels;

namespace StocksApp.ViewComponents
{
    public class SelectedStockViewComponent : ViewComponent
    {
        private readonly IFinnhubService _finnhubService;
        private readonly IConfiguration _configuration;

        public SelectedStockViewComponent(IFinnhubService finnhubService, IConfiguration configuration)
        {
            _finnhubService = finnhubService;
            _configuration = configuration;
        }
        public async Task<IViewComponentResult> InvokeAsync(string stockSymbol)
        {
            var companyProfileDictionary = await _finnhubService.GetCompanyProfile(stockSymbol);
            var stockQuoteDictionary = await _finnhubService.GetStockPriceQuote(stockSymbol);
            var stockTrade = new StockTrade
            {
                StockSymbol = companyProfileDictionary["ticker"].ToString(),
                StockName = companyProfileDictionary["name"].ToString(),
                Price = double.Parse(stockQuoteDictionary["c"].ToString().Replace('.', ',')),
                Logo = companyProfileDictionary["logo"].ToString(),
                Industry = companyProfileDictionary["finnhubIndustry"].ToString(),
                Exchange = companyProfileDictionary["exchange"].ToString()
                //<span class="pill">@Model["finnhubIndustry"]</span>
                //<h3 class="mb">Exchange: <span class="pill">@Model["exchange"]</span></h3>
            };
            return View(stockTrade);
        }
    }
}

StocksApp/Views/Shared/Components/SelectedStock/Default.cshtml
@model StocksApp.Models.StockTrade
@*<div style="position: sticky; top: 0; padding: 10px; border: 1px solid #ddd; border-radius: 8px; text-align: center; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    <div>
        <img src="@Model.Logo" alt="Stock Logo" style="width: 200px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);" />
        <h3 style="margin-top: 10px; font-size: 24px; color: #333; font-weight: bold;">@Model.StockName (@Model.StockSymbol)</h3>
        <h4 style="font-size: 18px; color: #666; margin-bottom: 10px;">@Model.Exchange</h4>
        <h4 style="font-size: 18px; color: #666; margin-bottom: 10px;">@Model.Industry</h4>
        <h1 style="font-size: 36px; color: #28a745; margin-top: 20px;">$@Model.Price</h1>
        <a href="~/Trade/Index/@Model.StockSymbol" style="text-decoration: none; display: inline-block; padding: 10px; background-color: #28a745; color: #fff; border-radius: 4px; transition: background-color 0.3s;">Trade Now</a>
    </div>
</div>*@
<div style="position: sticky; top: 0; padding: 10px; border: 1px solid #ddd; border-radius: 8px; text-align: center; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    <div>
        <!-- Placeholder для изображения (серый прямоугольник) -->
        <div style="width: 200px; height: 200px; background-color: #eee; border-radius: 8px; display: flex; align-items: center; justify-content: center; overflow: hidden; margin: 0 auto;">
            <!-- Используйте placeholder вместо изображения при загрузке -->
            <img src="@Model.Logo" alt="Stock Logo" style="width: 100%; height: auto; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); display: none;" onload="this.style.display='block';" />
        </div>
        <h3 style="margin-top: 10px; font-size: 24px; color: #333; font-weight: bold;">@Model.StockName (@Model.StockSymbol)</h3>
        <h4 style="font-size: 18px; color: #666; margin-bottom: 10px;">@Model.Exchange</h4>
        <h4 style="font-size: 18px; color: #666; margin-bottom: 10px;">@Model.Industry</h4>
        <h1 style="font-size: 36px; color: #28a745; margin-top: 20px;">$@Model.Price</h1>
        <a href="~/Trade/Index/@Model.StockSymbol" style="text-decoration: none; display: inline-block; padding: 10px; background-color: #28a745; color: #fff; border-radius: 4px; transition: background-color 0.3s;">Trade Now</a>
    </div>
</div>

StocksApp/Views/Shared/_BuyOrdersPartial.cshtml
@model ServiceContracts.DTO.BuyOrderResponse

<div style="margin: 10px; border: 2px solid grey; border-width: 0 0 2px 0; display: flex; flex-direction: column">
    <h4 style="margin: 0 0 10px 0">
        @Model.StockName (@Model.StockSymbol)
    </h4>
    <div>
        @Model.Quantity shares at $@Model.Price
    </div>
    <div>
        TradeAmount: $@Model.TradeAmount
    </div>
    <div>
        @Model.DateAndTimeOfOrder
    </div>
</div>

StocksApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>@ViewBag.Title</title>
</head>
<body style="margin: 0px; zoom: 110%">
    <div style="padding: 20px; background-color: lightgray; height: 15%; margin: 0px; display: flex; justify-content: space-between">
        <h3 style="font-size: 30px; margin: 0px">Stocks</h3>
        <div>
            <input style="resize: none; height: 100%; border-radius: 20px; padding-left: 10px;" type="text" id="urlInput" required />
            <button style="background-color: blue; border-radius: 15px; height: 100%; padding-left: 10px; padding-right: 10px" onclick="navigateToURL()">Find</button>
            <button style="background: lightgray; border: 0px;  height: 100%">@@</button>
            <button style="background-color: blue; border-radius: 15px; height: 100%; padding-left: 10px; padding-right: 10px">Login</button>
        </div>
    </div>
<div style="display: flex; margin: 10px;">
    <a href="/stocks/explore" style="font-size: medium; margin-right: 10px">Explore stocks</a>
    <a href="/" style="font-size: medium; margin-right: 10px">Trade</a>
    <a href="/trade/orders" style="font-size: medium; margin-right: 10px">Orders</a>
</div>
<div>
    @RenderBody()
</div>
<script>
    function navigateToURL() {
        var url = "trade/index/" + document.getElementById("urlInput").value;
        window.location.href = url;
    }
</script>

@await RenderSectionAsync("scripts", required:false);
</body>
</html>

StocksApp/Views/Shared/_SellOrdersPartial.cshtml
@model ServiceContracts.DTO.SellOrderResponse

<div style="margin: 10px; border: 2px solid grey; border-width: 0 0 2px 0; display: flex; flex-direction: column">
    <h4 style="margin: 0 0 10px 0">
        @Model.StockName (@Model.StockSymbol)
    </h4>
    <div>
        @Model.Quantity shares at $@Model.Price
    </div>
    <div>
        TradeAmount: $@Model.TradeAmount
    </div>
    <div>
        @Model.DateAndTimeOfOrder
    </div>
</div>

StocksApp/Views/Stocks/Explore.cshtml
@model System.Collections.Generic.List<StocksApp.ViewModels.Stock>

<div style="margin: 10px; display: flex; flex-direction: row; align-items: start;">
    <div style="width: 30%; padding: 10px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
        <ul style="list-style: none; padding: 0; margin: 0;">
            @foreach (var stock in Model)
            {
                <li style="margin-bottom: 10px;">
                    <a href="~/Stocks/Explore/@stock.StockSymbol" style="text-decoration: none; color: #333; display: block; padding: 10px; border: 1px solid #ddd; border-radius: 4px; transition: background-color 0.3s; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        <span style="font-weight: bold;">@stock.StockName</span>
                        <div style="font-size: 12px; color: #666;">(@stock.StockSymbol)</div>
                    </a>
                </li>
            }
        </ul>
    </div>
    <div style="width: 69%;position: relative; margin: 10px">
        @if (ViewBag.StockSymbol != null)
        {
            @await Component.InvokeAsync("SelectedStock", ViewBag.StockSymbol)
        }
    </div>
</div>

StocksApp/Views/Trade/Index.cshtml
@model StocksApp.Models.StockTrade

<label class="label-margin">Stocks > @Model.StockName</label>

<form method="post">
    <div class="flex-container stock-frame">
        <div class="stock-info">
            <h1 class="font-color-blue">
                @Model.StockName
                (@Model.StockSymbol)
            </h1>
            <div class="flex">
                <h1 class="price"> $ @($"{Model.Price:F2}") </h1>
            </div>
        </div>

        <div class="new-order">
            <h3 class="new-order-title">New order</h3>
            <h4 class="quantity-label"> Quantity </h4>
            <input type="number" name="Quantity" asp-for="Quantity" min="1" max="100000" placeholder="Quantity" required="required" class="quantity-input" autofocus="autofocus" />
            
            <div class="button-container">
                <button type="submit" formaction="~/Trade/BuyOrder" class="buy-button">
                    <span>Buy</span>
                </button>
                <button type="submit" formaction="~/Trade/SellOrder" class="sell-button">
                    <span>Sell</span>
                </button>
            </div>

        </div>

        <input type="hidden" asp-for="StockSymbol" />
        <input type="hidden" asp-for="StockName" />
        <input type="hidden" asp-for="Price" id="price" />
        <input type="hidden" id="FinnhubToken" value="@ViewBag.FinnhubToken" />

    </div>
</form>


@section scripts
{
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/FinnhubScript.js"></script>
}

StocksApp/Views/Trade/Orders.cshtml
@model StocksApp.ViewModels.Orders

<label class="header-label">Stocks > Orders</label>
<div class="flex-container" style="align-items: start">
    <div class="order-container" >
        <h4 class="order-header">Buy Orders</h4>
        @foreach (var buyOrder in Model.BuyOrders)
        {
            <partial name="_BuyOrdersPartial" model="buyOrder"></partial>
        }
    </div>
    <div class="order-container">
        <h4 class="order-header">Sell Orders</h4>
        @foreach (var sellOrder in Model.SellOrders)
        {
            <partial name="_SellOrdersPartial" model="sellOrder"></partial>
        }
    </div>
</div>